# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241023-205757-extended-seed

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
  - name: WhitespaceTokenizer #tokens
  - name: RegexFeaturizer #expresiones regulares
  - name: LexicalSyntacticFeaturizer #prefijos-sufijos-combinaciones
  - name: CountVectorsFeaturizer #texto en vectores [1,1,1]
  - name: CountVectorsFeaturizer #n-gramas caracteres, h-ho-hol
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier #modelo principal de RASA
    epochs: 100
  - name: FallbackClassifier #mensajes
    threshold: 0.7 #0.7 0.3
    ambiguity_threshold: 0.1
  - name: RegexEntityExtractor
    patterns:
    - name: number
      pattern: '\\d+'

policies: 
  - name: MemoizationPolicy #memoriza secuencias exactas
  - name: RulePolicy #reglas especificas
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
  #- name: UnexpecTEDIntentPolicy #respuestas que el modelo no predice bien
    max_history: 4
    epochs: 80
  - name: TEDPolicy #conversaciones largas memoria
    max_history: 4
    epochs: 80
    constrain_similarities: true

http_server:
  enabled: true
  port: 5005
  cors_origins: "*"
  webhook_url: "/webhooks/rest/webhook"  
  error_handling:
    default_handling: true
  response_headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "HEAD,GET,POST,OPTIONS,DELETE,PUT"